config/routes.rb
Rails.application.routes.draw do
  resources :jobs
  root 'jobs#index'
  # get 'jobs/index'

  # get 'jobs/new'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ActiveRecord::Base
  validates :title, presence: true
  validates :company, presence: true
  validates :url, presence: true, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  	def index
	  	@jobs = Job.page(params[:page]).per(9)
	end

  	def new
  		@job = Job.new
  	end

  	def create
	  	@job = Job.new(params.require(:job).permit(:title, :company, :url))
	  	if @job.save
	    	redirect_to root_path
	  	else
	    	render "new"
	  	end
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/jobs/index.html.erb
<div class="container">
	
	<h1><b>Jobs</b></h1>
	<p ><%= link_to "POST A JOB", new_job_path, class: "button" %></p>
	<div class="jobDiv">
  <table>
  <tr>
    <th >Title</th>
    <th>Company</th>
    <th>Link</th>
  </tr>
		<% @jobs.each_with_index do |job, index| %>
  		<tr>
  			<td><b><%= job.title %></b></td>
  			<td><%= job.company %></td>
  			<td><%= link_to job.url, :class=> "link" %></td>	
  		</tr>
  		<% end %>
      </table>
	</div>
  <p align="right">E. Espina</p>

</div>

app/views/jobs/new.html.erb
<div class="newJob">
	<div class="panelHeading" >	
	<center><h2><b>Create New Job</b></h2></center>	  		
  	</div>
  	<div class="panelBody">	
  		<%= simple_form_for @job , html: { class: "form-horizontal"} do |form| %>
	  	<div class="form-group">
	  		<%= form.input :title, label: "Job title" %>
	  	</div>
	  	<div class="form-group">
	  		<%= form.input :company, label: "Your company" %>
	  	</div>
	  	<div class="form-group">
	 		<%= form.input :url, label: "Link to job" %>
	  	</div>
	  	<center>	
	  		<%= form.button :submit, label: "Post Job", class: "button"%>
	  	</center>	  	
	  	
		<% end %>
  	</div>
</div>
</br><p align="right"><%= link_to "BACK TO JOBS", root_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  	<head>
    	<title>Jobs Board Application</title>
    	<%= favicon_link_tag 'jobLogo.png' %>
      	<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  	<%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  	<%= csrf_meta_tags %>
  	</head>
  	<body>
    <%= yield %>
  	</body>
</html>